//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectSQLServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int id { get; set; }
        public string nama { get; set; }
        public int jumlah { get; set; }
        public int subtotal { get; set; }
        public int order_id { get; set; }
        public int menu_id { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual pemesanan pemesanan { get; set; }
    }
}
